services:
  kea-dhcp-web:
    container_name: kea-dhcp-web
    network_mode: host
    cap_add:
      - NET_ADMIN
    image: blacknail/kea-dhcp-web:latest
    labels:
      createdBy: Apps
    restart: unless-stopped
    ports:
      - 18240:18240
    volumes:
    - ${CONF_PATH}:/etc/kea/kea-dhcp4.conf
    - ${SERVER_CODE_PATH}:/app