services:
  kea-dhcp:
    build: ${REPO_PATH}/Dockerfile
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ${REPO_PATH}/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf
      - ${REPO_PATH}/app:/app
    restart: unless-stopped